services:
  identity:
    build: ./identity
    restart: always
    develop:
      watch:
        - action: sync
          path: ./identity
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./identity/package.json
        - action: rebuild
          path: ./identity/Dockerfile
    environment:
      DATABASE_URL: postgres://identity:identity@identity-db:5432/identity
    depends_on:
      identity-db:
        condition: service_healthy
        restart: true

  identity-db:
    image: postgres:alpine
    restart: always
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity -d identity"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  stores:
    build: ./stores
    restart: always
    develop:
      watch:
        - action: sync
          path: ./stores
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./stores/package.json
        - action: rebuild
          path: ./stores/Dockerfile
    environment:
      DATABASE_URL: mongodb://stores:stores@stores-db:27017
    depends_on:
      stores-db:
        condition: service_healthy
        restart: true

  stores-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: stores
      MONGO_INITDB_ROOT_PASSWORD: stores
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - identity
      - stores
    develop:
      watch:
        - action: sync+restart
          path: reverse-proxy/nginx.conf
          target: /etc/nginx/nginx.conf
  web-app:
    build: ./web-app
    restart: always
    ports:
      - "4321:4321"
    develop:
      watch:
        - action: sync
          path: ./web-app
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./web-app/package.json
        - action: rebuild
          path: ./web-app/Dockerfile
volumes:
  identity-db-data:
