FROM node:23-alpine

USER node

WORKDIR /app
COPY package.json ./
RUN npm install

COPY --chown=node:node . /app

run npm run build

ENV PORT=4321
ENV HOST=0.0.0.0

CMD ["node", "./dist/server/entry.mjs"]
